version: '3'
services:
  qaas:
    build:
      context: .
      dockerfile: ./Dockerfile
    command: ["sh", "/code/run.sh"]
    env_file:
      - .env
    volumes:
    - .:/code
    ports:
      - 8000:8000
    depends_on:
      - smtp-server
      - redis
  smtp-server:
    image: mailhog/mailhog
    expose:
      - 1025
      - 8025
    ports:
      - '1025:1025'
      - '8025:8025'
  redis:
    image: redis:alpine
    ports:
      - "6379:6379"
    expose:
      - 6379
  celery:
    build:
      context: .
    command: celery -A qaas worker --loglevel=info
    env_file:
      - .env
    volumes:
      - .:/code
    depends_on:
      - redis
      - qaas

