# Generated by Django 3.2.12 on 2022-03-28 16:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("quiz", "0005_quizparticipant_score"),
    ]

    operations = [
        migrations.RenameField(
            model_name="quizinvitation",
            old_name="created",
            new_name="created_at",
        ),
    ]
