# Generated by Django 3.2.12 on 2022-03-29 15:31

import taggit.managers
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("taggit", "0004_alter_taggeditem_content_type_alter_taggeditem_tag"),
        ("quiz", "0006_rename_created_quizinvitation_created_at"),
    ]

    operations = [
        migrations.AlterField(
            model_name="quiz",
            name="tags",
            field=taggit.managers.TaggableManager(
                blank=True,
                help_text="A comma-separated list of tags.",
                through="taggit.TaggedItem",
                to="taggit.Tag",
                verbose_name="Tags",
            ),
        ),
        migrations.AlterUniqueTogether(
            name="answer",
            unique_together={("question", "answer")},
        ),
    ]
