# Generated by Django 3.2.12 on 2022-03-29 18:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("quiz", "0007_auto_20220329_1531"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="quizparticipant",
            name="completed_at",
        ),
    ]
