# Generated by Django 3.2.12 on 2022-03-30 04:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("quiz", "0008_remove_quizparticipant_completed_at"),
    ]

    operations = [
        migrations.AddField(
            model_name="quizparticipant",
            name="notified",
            field=models.BooleanField(default=False),
        ),
    ]
